services:
  preditivo:
    build: .
    container_name: climacta_preditivo
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8001:8001"
    networks:
      - preditivo_net

networks:
  preditivo_net:
    driver: bridge